site_name: Work CheatSheet

pages:
  - Home: index.md
  - docs:
    - shell: shell.md
    - visual studio: vs.md
    - vim: vim.md
    - sublime: sublime.md
    - git: git.md
    - gdb: gdb.md
    - cmake: cmake.md
    - makefile: makefile.md
    - svn: svn.md
  - work:
    - gm命令: 'work/gm.md'
    - path: 'work/path.md'
    - WorkCheateSheet: 'work/WorkCheatsheet.md'
    - question & anwser: 'work/qa.md'
  - server:
    - 开发环境搭建: server/开发环境搭建.md
    - 发版与热更: server/发版与热更.md
    - code snippets:
        - 小片段: server/small_code_snippets.md
    - 流程:
        - 基础流程: server/基础流程.md
        - 逻辑流程: server/逻辑流程.md
        - 战斗流程: server/战斗流程.md
  - client:
    - code snippets: client/code_snippets.md
    - tmp: client/tmp.md