site_name: Work CheatSheet

copyright: 'Copyright &copy; 2018 Diwen Liu'

repo_url: https://github.com/demon90s/Work_Cheatsheet
edit_uri: ""

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

pages:
  - Home: index.md
  - docs:
    - shell: shell.md
    - bat: bat.md
    - visual studio: vs.md
    - vim: vim.md
    - sublime: sublime.md
    - git: git.md
    - gdb: gdb.md
    - cmake: cmake.md
    - makefile: makefile.md
    - svn: svn.md
  - work:
    - gm命令: work/gm.md
    - path: work/path.md
    - WorkCheateSheet: work/WorkCheatsheet.md
    - question & anwser: work/qa.md
  - server:
    - 开发环境搭建: server/开发环境搭建.md
    - 发版与热更: server/发版与热更.md
    - coding tipes: server/coding_tips.md
    - code snippets:
        - def: server/code_snippets/def.md
        - config: server/code_snippets/config.md
        - msg: server/code_snippets/msg.md
        - role_system: server/code_snippets/role_system.md
        - 小片段: server/code_snippets/small_code_snippets.md
    - 流程:
        - 基础流程: server/基础流程.md
        - 逻辑流程: server/逻辑流程.md
        - 战斗流程: server/战斗流程.md
  - client:
    - code snippets: client/code_snippets.md
    - tmp: client/tmp.md